version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
